# Generated by Django 4.0.6 on 2023-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsibilities', models.TextField(blank=True, max_length=2000, null=True, verbose_name='обязанности')),
                ('requirements', models.TextField(blank=True, max_length=2000, null=True, verbose_name='требования')),
                ('conditions', models.TextField(blank=True, max_length=2000, null=True, verbose_name='условия')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('vacancies', models.ManyToManyField(related_name='companies', to='job_app.vacancy')),
            ],
        ),
    ]
