# Generated by Django 4.0.6 on 2023-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vacancies',
            field=models.ManyToManyField(null=True, related_name='companies', to='job_app.vacancy'),
        ),
    ]
