# Generated by Django 4.0.6 on 2023-06-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_alter_company_vacancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='job_app.company'),
        ),
    ]
