# Generated by Django 4.0.6 on 2023-06-07 14:12

from django.db import migrations, models
import job_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_remove_company_vacancies_vacancy_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=job_app.models.image_company_directory_path),
        ),
    ]
