# Generated by Django 4.0.6 on 2023-06-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_company_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
