# Generated by Django 4.0.6 on 2023-05-22 14:19

import auth_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_created=True)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('passport', models.CharField(max_length=20)),
                ('passport_region', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=auth_profile.models.profile_picture_directory_path)),
                ('study_type', models.CharField(blank=True, max_length=30, null=True)),
                ('study_place', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('experience', models.BooleanField()),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('archived', models.BooleanField(default=False)),
                ('archivist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivist', to='auth_profile.employee')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrar', to='auth_profile.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'ordering': ['-pk'],
            },
        ),
    ]
