# Generated by Django 4.0.6 on 2023-05-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
