# Generated by Django 4.0.6 on 2023-05-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_update',
        ),
    ]
