# Generated by Django 4.0.6 on 2023-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0003_remove_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
