# Generated by Django 4.0.6 on 2023-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0005_alter_profile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100),
        ),
    ]
