# Generated by Django 4.0.6 on 2023-05-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0006_alter_profile_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='archivist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivist', to='auth_profile.employee'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrar', to='auth_profile.employee'),
        ),
    ]
