# Generated by Django 4.0.6 on 2023-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0008_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='auth_profile.professions'),
        ),
    ]
