# Generated by Django 4.0.6 on 2023-06-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0009_profile_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='professions',
        ),
    ]
